### ISSUE TITLE
SolarCraft Crash Error

### ISSUE THREAD

**Issue by FluffyTheFurry** [FINDERFEED/SolarCraftRepository#10]
When i try to get an item from the creative inventory of SolarCraft the game freezes and crashes. When the game crashes it appears that error: java.lang.RuntimeException: MUDA MUDA MUDA MUDA MUDA 
The crash log:
[crash-2021-12-08_00.57.37-client.txt](https://github.com/FINDERFEED/SolarCraftRepository/files/7676158/crash-2021-12-08_00.57.37-client.txt)

**Comment by FINDERFEED** [comment]
What item caused this?

**Comment by FluffyTheFurry** [comment]
Okay now the crash has gotten worse, first it was crashing when i picked an item from a tab(which i dont remember) and now when i click on a tab it crashes, here some of them: Fragment Tab,Solar Craft Other Tab, Solar Craft Blocks Tab, Solar Craft Materials, Solar Craft Weapons Tab and Solar Craft Tools Tab. Every tab crashes when i click on it, the version i am playing is on 1.18

**Comment by FINDERFEED** [comment]
Wait some time, i will take a closer look when i get home. What i can say right now: Temporarily delete "Legendary Tooltips" mod, because it seems that it has some problems with my tooltips.

**Comment by FluffyTheFurry** [comment]
Alright thanks, btw love the mod you have created

**Comment by FluffyTheFurry** [comment]
Other crash report without the "Legendary Tooltips"
[crash-2021-12-08_15.50.33-client.txt](https://github.com/FINDERFEED/SolarCraftRepository/files/7676443/crash-2021-12-08_15.50.33-client.txt)

**Comment by FINDERFEED** [comment]
So, i got home, i will try debugging right now. (what i can say now - your latest crash is caused because of architectury api).

**Comment by FluffyTheFurry** [comment]
Alright, i removed Architectury api.

**Comment by FINDERFEED** [comment]
I think found the source of the problem, its my fault. I will release a fix soon.

**Comment by FluffyTheFurry** [comment]
Alright thanks

**Comment by FINDERFEED** [comment]
![image](https://user-images.githubusercontent.com/75111661/145235190-fa3fae56-8663-4aba-8e23-7222ee85e16e.png)

Fixed! Should be available for download now!

**Comment by FluffyTheFurry** [comment]
Okay thanks!
