### ISSUE TITLE
Crashes when clicking on a tab

### ISSUE THREAD

**Issue by FluffyTheFurry** [FINDERFEED/SolarCraftRepository#11]
It probably from the new mobs or optifine messes it, I don't know but here the crash log.
[crash-2021-12-09_14.29.12-client.txt](https://github.com/FINDERFEED/SolarCraftRepository/files/7685068/crash-2021-12-09_14.29.12-client.txt)

**Comment by FINDERFEED** [comment]
Its the same crash i have already fixed yesterday. As i see from crash report you are using 2.1.1 version of SolarCraft, the latest is 2.1.2.

**Comment by FluffyTheFurry** [comment]
I added 2.1.2 but i guess something did has gone wrong when adding it

**Comment by FluffyTheFurry** [comment]
Sorry for opening a ticket for a dumb thing

**Comment by FluffyTheFurry** [comment]
Thank you

**Comment by FluffyTheFurry** [comment]
Actually found the issue why its on 2.1.1. when i changed to 2.1.2. the Curseforge app wants update it to 2.1.1. So I have clicked the update button without noticing it downgraded the version.
