### ISSUE TITLE
Optifine Rendering Issue

### ISSUE THREAD

**Issue by PepGames** [FINDERFEED/SolarCraftRepository#12]
Hey man! So I'm over here debugging my custom modpack. And I ended up running into a bug with your Solar Craft Mod. So, specifically this bug occurs only when using SHADERS with Optifine. But the "Rune Energy Pylon"s cause a weird rendering bug that makes your terrain turn black when you're within rendering distance of the "Rune Energy Pylon". I attached a photo of what it looks like. This happens with ALL shaders. Once the "Rune Energy Pylon" block is destroyed, the shaders function properly again with zero issues. So it is the pylons causing it. 

You may or may not want to resolve this bug, but I just figured I'd at least make you aware of it. I've removed the mod from my modpack for now, but let us know if you fix this bug!
![runepylonbug](https://user-images.githubusercontent.com/85426927/146125041-95c4d198-b781-4dc6-be7e-9d6009d3ad24.PNG)

EDIT: 1.18.1 btw
EDIT2: FML v39, ALL Optifine versions do this.

**Comment by FINDERFEED** [comment]
I am using my own shaders for the special effects(idk why they cause this strange bug, since they are made like in vanilla mc(json shaders)). I will try to fix this but i cant guarantee that it will be fixed.(i am not a professional in rendering+optifine is closed source project).

**Comment by PepGames** [comment]
no problem dude! I know not everyone uses shaders on optifine, but yea definitely let us know :) thanks for your time.

**Comment by FINDERFEED** [comment]
Hi! (I havent had time to test it). So i have tried to install shaders myself and everything is workng except for some reason all shaders from my mod are just not working. Idk why are you having this strange problem, everything is fine for me. (I am testing with BSL shaders) (i have downloaded the latest optifine)
![image](https://user-images.githubusercontent.com/75111661/148645748-d36f21b4-5b18-461c-8ff8-d6faa56823f5.png)
