### ISSUE TITLE
crash serveur 1.18.1

### ISSUE THREAD

**Issue by laboriens** [FINDERFEED/SolarCraftRepository#15]
forge 1.18.1 39.0.66
solar craft: 2.3

solar craft mod crashes forge launch 1.18.1 39.0.66
logs: https://textup.fr/612024Zk
forge forum discussion: https://forums.minecraftforge.net/topic/108484-1181-failed-to-start-the-minecraft-server/

I put the mods one by one to see which one crashes since it doesn't say what and what the solar craft mod

log2 when I found the solar craft mod which prevents from starting server https://textup.fr/612412Db

**Comment by FINDERFEED** [comment]
Hello! The log doesnt open for me but i think i know what is the problem. Forge has changed the registries of trunk and leaves placers in 39.0.66 version, but i havent updated to it yet. Maybe thats why it launches on 39.0.65 and crashes on 39.0.66. Use older forge version for now if its possible.

**Comment by laboriens** [comment]
not possible because many mods are upgraded to version 66

**Comment by FINDERFEED** [comment]
Then wait for me to update to the new forge version. I will do it tomorrow or in ~3 days.

**Comment by laboriens** [comment]
okay.  just I feel like it's server side only

**Comment by FINDERFEED** [comment]
Hi! I have released a 2.4 update and updated the forge version with it(tested it and the server do start normally).
