### ISSUE TITLE
Game crashes when breaking Infuser stand

### ISSUE THREAD

**Issue by Tonomo** [FINDERFEED/SolarCraftRepository#18]
When breaking the Infuser stand the game crashes, this happens in both survival and creative.

**This is the report from minecraft:**
The game crashed whilst rendering block entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraftforge.items.ItemStackHandler.getStackInSlot(int)" because the return value of "com.finderfeed.solarforge.magic.blocks.infusing_table_things.infusing_pool.InfusingStandTileEntity.getInventory()" is null
Avslutningskod: -1

**This is the crash report:**
[crash-2022-03-13_18.17.05-client.txt](https://github.com/FINDERFEED/SolarCraftRepository/files/8240236/crash-2022-03-13_18.17.05-client.txt)

**Comment by FINDERFEED** [comment]
Oh i know why this is happening. Will be fixed in the next update.
