### ISSUE TITLE
Suggestion: Configure Max Enchantment level

### ISSUE THREAD

**Issue by clubpetey** [FINDERFEED/SolarCraftRepository#19]
Mods like Apotheosis extend the standard enchantments (and add some of their own) to Level X (10).  however the SolarCraft Enchanting Table only allows for enchanting the default levels.  I think either a config option in the Enchantment JSON file that specified the max level, or have the mod auto-recognize the max level based on the books that exist would be a great addition that would take not a lot of effort.

For balance, the amounts required to enchant could (optionally) follow an exponential curve.

**Comment by FINDERFEED** [comment]
Thats a good idea, started working on it.  (but honestly i have no idea how to detect max enchantment level based on books)

**Comment by FINDERFEED** [comment]
Done.
