### ISSUE TITLE
Suggestion - 1.18.1 - config option to remove starting messages

### ISSUE THREAD

**Issue by DWX12** [FINDERFEED/SolarCraftRepository#20]
I haven't tried any version of Solarcraft past 1.18.1 so this might not be an issue any more. However, with 1.18.1 there is a starting message of "Thanks for download..." and "If you were playing before...". Would like to see a config option to disable all starting messages.

For those that create modpacks, these types of messages can be distracting especially seeing them over and over again. Also the message doesn't really apply to those that are using "solarcraft-1.18.1-2.4.2" and haven't used any previous versions.

Again, this may not apply to 1.18.2, but at the moment, I'm sort of stuck on version 1.18.1 with the modpack I'm working on and am not able to update to 1.18.2 at this time.

Thank you for all the time and effort put into creating this mod.

**Comment by FINDERFEED** [comment]
Hello! Yes there is already a client config option in the latest version to disable those messages. I can try to add it on 1.18.1 version when i will have time on it. (The only issue is that i just haven't created a 1.18.1 branch when updating to 1.18.2 so i will need to find a correct commit)

**Comment by FINDERFEED** [comment]
Done

**Comment by DWX12** [comment]
Thank you very much for completing this.
