### ISSUE TITLE
Add config for yellow beacon frequency

### ISSUE THREAD

**Issue by freopt** [FINDERFEED/SolarCraftRepository#21]
They're a bit too common in my opinion. As far as I can see they aren't registered as a structure so it can't be changed with datapacks either.

**Comment by FINDERFEED** [comment]
They are registered as a Feature. Is it possible to override my pylon configured feature with a datapack(i am just not familiar with them)?

**Comment by freopt** [comment]
Anything set in [resources](https://github.com/FINDERFEED/SolarCraftRepository/tree/master/src/main/resources) can be overridden with datapacks, I don't see pylons here so a config option would be nice.

**Comment by FINDERFEED** [comment]
I asked in MMD and they said that its possible to override a code-registered configured features with a datapack, so its unnecesarry doing a config option. You can find all "feature ids" in FeaturesRegistry class. (Note that my pylon automatically seeks for a surface spot so you just need to adjust the spawn probability)

**Comment by FINDERFEED** [comment]
Done
