### ISSUE TITLE
Pylon generated inside village house

### ISSUE THREAD

**Issue by freopt** [FINDERFEED/SolarCraftRepository#22]
![image](https://user-images.githubusercontent.com/45438411/163635507-45c95d18-9763-4f7e-85fd-19ecb8a30b26.png)
![image](https://user-images.githubusercontent.com/45438411/163635528-300a1217-7eed-4b31-9d31-8b604ab10359.png)

**Comment by FINDERFEED** [comment]
Hmmm its strange. I am using a generation step before surface structures. I will try to fix it.

**Comment by FINDERFEED** [comment]
I hope i fixed it. At least i haven't encountered this anymore.
