### ISSUE TITLE
[1.18.2] /Fly command issues

### ISSUE THREAD

**Issue by YOYOK9** [FINDERFEED/SolarCraftRepository#25]
Have noticed an odd bug between SolarCraft and mods that add the /fly command. In my case I am using ServerUtilities. Basically what happens in when I enable /fly everything works as it should until I either equip or remove any chestplate, and this can be any chestplate, even vanilla ones. Once the chestplate slot has changed I drop to the ground and my /fly removed. 

One thing I did notice in testing is once I equipped the Solar chestplate the issue stopped. I could equip/remove any type of chestplate while flying and not fall to the ground. 

Replication: 
1: Create a creative world
2: get any chestplate
3: enter survival 
4: do /fly and fly up a few blocks
5: equip chestplate (or remove if equipped in creative)

Mods:
solarcraft-1.18.2-2.7
Server_Utils-1.18.1-2.3.5
forge: 40.1.19

I have checked both latest & debug logs. Neither show any signs of issues. (had to test a mod at a time to figure out it was SolarCraft)

**Comment by FINDERFEED** [comment]
Oh. I know why this is happening, and its easily fixable. Haven't thought of this behaviour.
(P.S. It happens because in survival if player puts on Divine Chestplate i give him creative flight, if player unequips Divine Chestplate or equips any other armor - flight is removed)

**Comment by YOYOK9** [comment]
Any update on this? We have a temp fix going but it's a pain to keep re-enabling fly or toggling the chestplates that apply fly that aren't from your mod. And unfortunately can't just remove the mod as it breaks the server world (also don't want too, we like the mod).

**Comment by FINDERFEED** [comment]
I am currently getting ready for very important exams so i dont have much time. I will try to find some to release a small 2.7.1 update with a fix, maybe tomorrow.

**Comment by FINDERFEED** [comment]
Forgot to close this oups
