### ISSUE TITLE
Solar Lexicon Gui Issue

### ISSUE THREAD

**Issue by orionSquared** [FINDERFEED/SolarCraftRepository#27]
Good evening,

Love this mod so far, I'm planning to put it into my new modpack. I do notice an issue though. The Solar Lexicon has a weird GUI issue. It seems that there's no way for me to resize it. There are clearly some achievement boxes that are "off screen" in the lexicon as some are cut off and there are lines that are pointing to boxes that I can't see. I don't see any way of moving that area within the lexicon for me to see them or any way to scroll over. I've also tried changing my GUI settings for minecraft and all it does is resize the entire window, and the achievements are still out of view.

I'm seeing this issue on both the beacon icon page as well as the block icon page. So far the crafting table page isn't having the issue, but I'd assume that when I learn more runes, it will eventually have the same issue.

**Comment by FINDERFEED** [comment]
Sorry for such a late reply. Can you clarify whats exactly wrong? Everything is okay on my side. 

https://user-images.githubusercontent.com/75111661/185086081-0c209066-ea33-45cc-b483-cc05b3728e72.mp4
