### ISSUE TITLE
[1.18.2] Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by aking4125** [FINDERFEED/SolarCraftRepository#28]
Hello,

Upon updating Solarcraft to version 40.1.80-2.8. The server hangs with the above message buried within the log (Along with a Datapack error). The server no longer continues beyond this point but doesn't generate a crash report. I suspect a conflict somewhere. 

However downgrading to 2.7.1 fixes this issue and the server continues normally. Doesn't matter if it's previous world or newly generated world. This affects the server only, client works fine.

Any ideas?

[debug.log](https://github.com/FINDERFEED/SolarCraftRepository/files/9706461/debug.log)

**Comment by FINDERFEED** [comment]
Oups, it seems thats its my fault. When i will have time i will fix it.
