### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by JojoMeowstic** [FINDERFEED/SolarCraftRepository#3]
Currently crashes when used with Corail Tombstone on 1.17.1 Forge.

**Comment by FINDERFEED** [comment]
Please provide a crash report so i know what exactly causes the crash.

**Comment by FINDERFEED** [comment]
Oh wait i saw the crash. It happens in Corail Tombstone classes(their repo is private :( )  so i cant do anything about it :( . I will try to contact the developer to solve the problem.

**Comment by JojoMeowstic** [comment]
Yeah, it's no huge thing just figured it was important to bring up. Considering how hard the crash is.

**Comment by FINDERFEED** [comment]
Okay i think i fixed it, at least it doesn't crash upon entering the world :)
