### ISSUE TITLE
Crash when a mob uses the Shield of Solar God

### ISSUE THREAD

**Issue by noncom** [FINDERFEED/SolarCraftRepository#33]
Hey, there's a crash.
Playing a modpack where mobs can carry and use items.
So one of them apparently got the Shield of Solar God and tried using it.
As I see the code doesn't anticipate that the user could be not a player: https://github.com/FINDERFEED/SolarCraftRepository/blob/master/src/main/java/com/finderfeed/solarcraft/content/items/ShieldOfSolarGod.java#L118
But hey, it's a `LivingEntity` originally, so why not :)

[crash-2023-02-12_00.22.29-server.txt](https://github.com/FINDERFEED/SolarCraftRepository/files/10714946/crash-2023-02-12_00.22.29-server.txt)

**Comment by FINDERFEED** [comment]
Oups i was not expecting that some other entity than the player will wield my shield xD.
