### ISSUE TITLE
runic_table interaction crashing on forge client when attempting to load gui

### ISSUE THREAD

**Issue by Arngue** [FINDERFEED/SolarCraftRepository#34]
when trying to open solarcraft:runic_table inventory/gui minecraft client crashes

-Forge build:  1.19.2-43.2.0
-Mod build: 3.0.2

To reproduce:
-enter single player creative world, put a runic table and trying to open it with comented versions.

[https://imgur.com/UYycjGf](url)
[https://imgur.com/RYJo6Z2](url)

stacktrace:
[https://justpaste.it/c75n1](url)

**Comment by FINDERFEED** [comment]
I don't experience this crash. Try to launch with solarcraft alone and see if the issue persists. If it does, try updating forge version, else some mod mess with containers.

**Comment by Arngue** [comment]
sorry, you're right, as i see in the stacktrace only solarcraft didn't think about other mods, it's some mod messing with containers.

ty for your response!
