### ISSUE TITLE
Cant find SolarCraft biomes

### ISSUE THREAD

**Issue by TheButterbrotMan** [FINDERFEED/SolarCraftRepository#35]
Hello, in my modpack on 1.18.2 forge, i am unable to locate/find any biomes of SolarCraft.

Could this be connected to TerraBlender?

This is my modpack: https://beta.curseforge.com/minecraft/modpacks/dragonsreach

**Comment by FINDERFEED** [comment]
Uhmmm there are no overworld biomes in solar craft.
