### ISSUE TITLE
Cant decrypt fragments

### ISSUE THREAD

**Issue by TinaLuwten** [FINDERFEED/SolarCraftRepository#39]
I'm not sure if I've missed something but i cant use the runic table to decrypt ancient fragments i have more then enough runes and fragments but the tiles that you get rid of in the runic table menu don't show up i can only decrypt until i get the advanced crafting table have i just not progressed far enough or is this a bug

**Comment by FINDERFEED** [comment]
Does it say "No fragments available"?

**Comment by TinaLuwten** [comment]
yeah even when i put a fragment in it

**Comment by FINDERFEED** [comment]
Complete progression stages

**Comment by TinaLuwten** [comment]
yeah i thought that was the issue cause when i killed the dragon it let me decrpt a few but then it stopped again so i guess im just not far enough in the mod still though thanks
