### ISSUE TITLE
too many shrin structures?

### ISSUE THREAD

**Issue by knoxhack** [FINDERFEED/SolarCraftRepository#43]
are they supposed to be spawning that many of these?

https://i.imgur.com/amX2KqK.png
[https://i.imgur.com/amX2KqK.png](https://i.imgur.com/amX2KqK.png)

**Comment by FINDERFEED** [comment]
If you feel that they are spawning too frequently - you can change their spawn chance in mod config (they are called Pylons). Also there are only two of them in the screenshot, not too much.
