### ISSUE TITLE
Crash when starting the game

### ISSUE THREAD

**Issue by Uraneptus** [FINDERFEED/SolarCraftRepository#5]
The game crashes when I start it.
I have only SolarCraft installed and i'm on forge version 37.0.27, but it also doesn't work on forge version 37.0.25
Here's the crash report:
https://pastebin.com/3R9DFvT6

**Comment by FINDERFEED** [comment]
If i remember correctly 1.6.2 mod version was released before 37.0.25 forge. Why it is crashing is because forge renamed one thing to match vanilla style in 37.0.25 update and 1.6.2 version of the mod currently doesnt work on it. Use the lower forge version.

**Comment by FINDERFEED** [comment]
(i think i will not be able to release the fix soon, i am currently working on an update and idk when it will come out, maybe in ~2-5 days, depends on my lazyness xD)

**Comment by Uraneptus** [comment]
Alright, thank you :D

**Comment by FINDERFEED** [comment]
I released a new version, everything should be working fine now!
