### ISSUE TITLE
I dont understand this

### ISSUE THREAD

**Issue by stradar21** [FINDERFEED/SolarCraftRepository#6]
So im trying to figure out your mod but I have no idea how to craft these items or even how to unlock them I used the command unlock all and tried to use the runic table but it does nothing??!! Is there some kind of way we can get some better documentation on this mod or some kind of video? Because I have no idea what im doing when it comes to this mod.

**Comment by FINDERFEED** [comment]
Do you have solar lexicon?

**Comment by stradar21** [comment]
Yes but I have no clue what I am doing lol

**Comment by FINDERFEED** [comment]
Lexicon has a second page with information that is built based on the ancient fragments you have inside it(to put them here shift-right click with lexicon, it will open its inventory (then shift-click the fragment item)). To get ancient fragments you need a blank fragment which can be found in ruins or dungeons and runes.(if it doesn't unlock anything then you need to complete some progressions and more fragments will be available to be unlocked)

**Comment by stradar21** [comment]
I unlocked all the progression to test the mod out also I spawned in a blank Fragment and put in the runes in according to the runic table but nothing happens when I unlocked all the progression is this a bug? I have no idea also how to craft any of the gear and tools.

**Comment by FINDERFEED** [comment]
If you have used /solarcraft fragments unlockall command then its not a bug because this command gives all fragment data to player. To test the mod use /solarcraft fillLexicon with a lexicon in your hand, it will fill the lexicon with all fragments.

**Comment by stradar21** [comment]
So I do that command and then I can craft items?

**Comment by FINDERFEED** [comment]
Then you can look at the crafting recipes inside the lexicon. (To move inside it use arrows)

**Comment by stradar21** [comment]
/solarcraft fillLexicon does not work 

Ok so I tried to click the craft button and it crashes my client not the server is this commonly known issues?

**Comment by FINDERFEED** [comment]
No, i am hearing it for the first time. Could you please send a crashreport?(use pastebin.com).(And what "craft" button do you mean?). Also i recorded a video on the main mod page where i show how to use lexicon/runic table/infuser.

**Comment by FINDERFEED** [comment]
Issue closed because no information about crash was provided.
