### ISSUE TITLE
Stuck Making radiant Curias

### ISSUE THREAD

**Issue by aburone** [FINDERFEED/SolarCraftRepository#9]
The recipe looks good, I click it with the Wand, the effects start and never completes.
I tried putting it under the Solar lens and even under a Pylon (pictured). No dice. I leaved there for 12 hours in case the thing needed to "charge" 
I'm out of ideas
https://imgur.com/gallery/rrxzb6j
Help?

Also there's a crash if I click on the master items. But it looks like you're not working on the 1.16 version anymore :(

**Comment by FINDERFEED** [comment]
If this recipe requires runic energy and you are on 1.16.5, you should use Runic Energy Repeaters to transmit pylon energy to the infuser(place it somewhere with a rune block underneath (it will define what energy rype this repeater should transmit))(in the latest 1.17.1 version all should work fine). And if i remember correctly this recipe requires solar energy too (meaning that you need a solar energy generator binded to infuser). P.S. solar lens is only used to craft qualadium and geminium(dont exist in 1.16) ingots. P.S.S 1.16 mod version is very unstable and could crash anywhere.(you are right, i am not working at it now and will not work in near future)
